model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[tools]
web_search = true

[mcp_servers.github]
command = "./scripts/github-mcp-proxy.sh"
args = []
